/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface SampleSubmission {
  'id' : string,
  'complianceCheckboxes' : {
    'nonClinicalUse' : boolean,
    'sampleSpecificResults' : boolean,
    'noHumanSamples' : boolean,
  },
  'city' : string,
  'sampleDetails' : {
    'solvent' : string,
    'concentration' : string,
    'preservatives' : string,
    'matrix' : string,
  },
  'name' : string,
  'sampleType' : SampleType,
  'email' : string,
  'notes' : string,
  'timestamp' : bigint,
  'organization' : string,
  'phone' : string,
  'testsRequested' : Array<TestCategory>,
  'preferredTurnaround' : Turnaround,
  'quantityAvailable' : bigint,
}
export type SampleType = { 'data' : null } |
  { 'food' : null } |
  { 'swab' : null } |
  { 'extract' : null } |
  { 'water' : null } |
  { 'product' : null };
export type TestCategory = { 'microbiology' : null } |
  { 'pesticides' : null } |
  { 'mycotoxins' : null } |
  { 'heavyMetals' : null } |
  { 'hormones' : null } |
  { 'nutrients' : null } |
  { 'residualSolvents' : null } |
  { 'vitamins' : null };
export type Turnaround = { 'urgent' : null } |
  { 'standard' : null };
export interface _SERVICE {
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getSampleSubmissions' : ActorMethod<[], Array<SampleSubmission>>,
  'submitContact' : ActorMethod<[string, string, string, string], undefined>,
  'submitSample' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      SampleType,
      Array<TestCategory>,
      {
        'solvent' : string,
        'concentration' : string,
        'preservatives' : string,
        'matrix' : string,
      },
      bigint,
      Turnaround,
      string,
      {
        'nonClinicalUse' : boolean,
        'sampleSpecificResults' : boolean,
        'noHumanSamples' : boolean,
      },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];