/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const SampleType = IDL.Variant({
  'data' : IDL.Null,
  'food' : IDL.Null,
  'swab' : IDL.Null,
  'extract' : IDL.Null,
  'water' : IDL.Null,
  'product' : IDL.Null,
});
export const TestCategory = IDL.Variant({
  'microbiology' : IDL.Null,
  'pesticides' : IDL.Null,
  'mycotoxins' : IDL.Null,
  'heavyMetals' : IDL.Null,
  'hormones' : IDL.Null,
  'nutrients' : IDL.Null,
  'residualSolvents' : IDL.Null,
  'vitamins' : IDL.Null,
});
export const Turnaround = IDL.Variant({
  'urgent' : IDL.Null,
  'standard' : IDL.Null,
});
export const SampleSubmission = IDL.Record({
  'id' : IDL.Text,
  'complianceCheckboxes' : IDL.Record({
    'nonClinicalUse' : IDL.Bool,
    'sampleSpecificResults' : IDL.Bool,
    'noHumanSamples' : IDL.Bool,
  }),
  'city' : IDL.Text,
  'sampleDetails' : IDL.Record({
    'solvent' : IDL.Text,
    'concentration' : IDL.Text,
    'preservatives' : IDL.Text,
    'matrix' : IDL.Text,
  }),
  'name' : IDL.Text,
  'sampleType' : SampleType,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'organization' : IDL.Text,
  'phone' : IDL.Text,
  'testsRequested' : IDL.Vec(TestCategory),
  'preferredTurnaround' : Turnaround,
  'quantityAvailable' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getSampleSubmissions' : IDL.Func([], [IDL.Vec(SampleSubmission)], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitSample' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        SampleType,
        IDL.Vec(TestCategory),
        IDL.Record({
          'solvent' : IDL.Text,
          'concentration' : IDL.Text,
          'preservatives' : IDL.Text,
          'matrix' : IDL.Text,
        }),
        IDL.Nat,
        Turnaround,
        IDL.Text,
        IDL.Record({
          'nonClinicalUse' : IDL.Bool,
          'sampleSpecificResults' : IDL.Bool,
          'noHumanSamples' : IDL.Bool,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const SampleType = IDL.Variant({
    'data' : IDL.Null,
    'food' : IDL.Null,
    'swab' : IDL.Null,
    'extract' : IDL.Null,
    'water' : IDL.Null,
    'product' : IDL.Null,
  });
  const TestCategory = IDL.Variant({
    'microbiology' : IDL.Null,
    'pesticides' : IDL.Null,
    'mycotoxins' : IDL.Null,
    'heavyMetals' : IDL.Null,
    'hormones' : IDL.Null,
    'nutrients' : IDL.Null,
    'residualSolvents' : IDL.Null,
    'vitamins' : IDL.Null,
  });
  const Turnaround = IDL.Variant({
    'urgent' : IDL.Null,
    'standard' : IDL.Null,
  });
  const SampleSubmission = IDL.Record({
    'id' : IDL.Text,
    'complianceCheckboxes' : IDL.Record({
      'nonClinicalUse' : IDL.Bool,
      'sampleSpecificResults' : IDL.Bool,
      'noHumanSamples' : IDL.Bool,
    }),
    'city' : IDL.Text,
    'sampleDetails' : IDL.Record({
      'solvent' : IDL.Text,
      'concentration' : IDL.Text,
      'preservatives' : IDL.Text,
      'matrix' : IDL.Text,
    }),
    'name' : IDL.Text,
    'sampleType' : SampleType,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'organization' : IDL.Text,
    'phone' : IDL.Text,
    'testsRequested' : IDL.Vec(TestCategory),
    'preferredTurnaround' : Turnaround,
    'quantityAvailable' : IDL.Nat,
  });
  
  return IDL.Service({
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getSampleSubmissions' : IDL.Func(
        [],
        [IDL.Vec(SampleSubmission)],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitSample' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          SampleType,
          IDL.Vec(TestCategory),
          IDL.Record({
            'solvent' : IDL.Text,
            'concentration' : IDL.Text,
            'preservatives' : IDL.Text,
            'matrix' : IDL.Text,
          }),
          IDL.Nat,
          Turnaround,
          IDL.Text,
          IDL.Record({
            'nonClinicalUse' : IDL.Bool,
            'sampleSpecificResults' : IDL.Bool,
            'noHumanSamples' : IDL.Bool,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };