/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactSubmission {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export interface SampleSubmission {
    id: string;
    complianceCheckboxes: {
        nonClinicalUse: boolean;
        sampleSpecificResults: boolean;
        noHumanSamples: boolean;
    };
    city: string;
    sampleDetails: {
        solvent: string;
        concentration: string;
        preservatives: string;
        matrix: string;
    };
    name: string;
    sampleType: SampleType;
    email: string;
    notes: string;
    timestamp: bigint;
    organization: string;
    phone: string;
    testsRequested: Array<TestCategory>;
    preferredTurnaround: Turnaround;
    quantityAvailable: bigint;
}
export enum SampleType {
    data = "data",
    food = "food",
    swab = "swab",
    extract = "extract",
    water = "water",
    product = "product"
}
export enum TestCategory {
    microbiology = "microbiology",
    pesticides = "pesticides",
    mycotoxins = "mycotoxins",
    heavyMetals = "heavyMetals",
    hormones = "hormones",
    nutrients = "nutrients",
    residualSolvents = "residualSolvents",
    vitamins = "vitamins"
}
export enum Turnaround {
    urgent = "urgent",
    standard = "standard"
}
export interface backendInterface {
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getSampleSubmissions(): Promise<Array<SampleSubmission>>;
    submitContact(name: string, email: string, phone: string, message: string): Promise<void>;
    submitSample(name: string, organization: string, email: string, phone: string, city: string, sampleType: SampleType, testsRequested: Array<TestCategory>, sampleDetails: {
        solvent: string;
        concentration: string;
        preservatives: string;
        matrix: string;
    }, quantityAvailable: bigint, preferredTurnaround: Turnaround, notes: string, complianceCheckboxes: {
        nonClinicalUse: boolean;
        sampleSpecificResults: boolean;
        noHumanSamples: boolean;
    }): Promise<void>;
}
import type { SampleSubmission as _SampleSubmission, SampleType as _SampleType, TestCategory as _TestCategory, Turnaround as _Turnaround } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getSampleSubmissions(): Promise<Array<SampleSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSampleSubmissions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSampleSubmissions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitSample(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: SampleType, arg6: Array<TestCategory>, arg7: {
        solvent: string;
        concentration: string;
        preservatives: string;
        matrix: string;
    }, arg8: bigint, arg9: Turnaround, arg10: string, arg11: {
        nonClinicalUse: boolean;
        sampleSpecificResults: boolean;
        noHumanSamples: boolean;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSample(arg0, arg1, arg2, arg3, arg4, to_candid_SampleType_n11(this._uploadFile, this._downloadFile, arg5), to_candid_vec_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_Turnaround_n16(this._uploadFile, this._downloadFile, arg9), arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSample(arg0, arg1, arg2, arg3, arg4, to_candid_SampleType_n11(this._uploadFile, this._downloadFile, arg5), to_candid_vec_n13(this._uploadFile, this._downloadFile, arg6), arg7, arg8, to_candid_Turnaround_n16(this._uploadFile, this._downloadFile, arg9), arg10, arg11);
            return result;
        }
    }
}
function from_candid_SampleSubmission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleSubmission): SampleSubmission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SampleType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleType): SampleType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TestCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestCategory): TestCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Turnaround_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Turnaround): Turnaround {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    complianceCheckboxes: {
        nonClinicalUse: boolean;
        sampleSpecificResults: boolean;
        noHumanSamples: boolean;
    };
    city: string;
    sampleDetails: {
        solvent: string;
        concentration: string;
        preservatives: string;
        matrix: string;
    };
    name: string;
    sampleType: _SampleType;
    email: string;
    notes: string;
    timestamp: bigint;
    organization: string;
    phone: string;
    testsRequested: Array<_TestCategory>;
    preferredTurnaround: _Turnaround;
    quantityAvailable: bigint;
}): {
    id: string;
    complianceCheckboxes: {
        nonClinicalUse: boolean;
        sampleSpecificResults: boolean;
        noHumanSamples: boolean;
    };
    city: string;
    sampleDetails: {
        solvent: string;
        concentration: string;
        preservatives: string;
        matrix: string;
    };
    name: string;
    sampleType: SampleType;
    email: string;
    notes: string;
    timestamp: bigint;
    organization: string;
    phone: string;
    testsRequested: Array<TestCategory>;
    preferredTurnaround: Turnaround;
    quantityAvailable: bigint;
} {
    return {
        id: value.id,
        complianceCheckboxes: value.complianceCheckboxes,
        city: value.city,
        sampleDetails: value.sampleDetails,
        name: value.name,
        sampleType: from_candid_SampleType_n4(_uploadFile, _downloadFile, value.sampleType),
        email: value.email,
        notes: value.notes,
        timestamp: value.timestamp,
        organization: value.organization,
        phone: value.phone,
        testsRequested: from_candid_vec_n6(_uploadFile, _downloadFile, value.testsRequested),
        preferredTurnaround: from_candid_Turnaround_n9(_uploadFile, _downloadFile, value.preferredTurnaround),
        quantityAvailable: value.quantityAvailable
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgent: null;
} | {
    standard: null;
}): Turnaround {
    return "urgent" in value ? Turnaround.urgent : "standard" in value ? Turnaround.standard : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    data: null;
} | {
    food: null;
} | {
    swab: null;
} | {
    extract: null;
} | {
    water: null;
} | {
    product: null;
}): SampleType {
    return "data" in value ? SampleType.data : "food" in value ? SampleType.food : "swab" in value ? SampleType.swab : "extract" in value ? SampleType.extract : "water" in value ? SampleType.water : "product" in value ? SampleType.product : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    microbiology: null;
} | {
    pesticides: null;
} | {
    mycotoxins: null;
} | {
    heavyMetals: null;
} | {
    hormones: null;
} | {
    nutrients: null;
} | {
    residualSolvents: null;
} | {
    vitamins: null;
}): TestCategory {
    return "microbiology" in value ? TestCategory.microbiology : "pesticides" in value ? TestCategory.pesticides : "mycotoxins" in value ? TestCategory.mycotoxins : "heavyMetals" in value ? TestCategory.heavyMetals : "hormones" in value ? TestCategory.hormones : "nutrients" in value ? TestCategory.nutrients : "residualSolvents" in value ? TestCategory.residualSolvents : "vitamins" in value ? TestCategory.vitamins : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SampleSubmission>): Array<SampleSubmission> {
    return value.map((x)=>from_candid_SampleSubmission_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestCategory>): Array<TestCategory> {
    return value.map((x)=>from_candid_TestCategory_n7(_uploadFile, _downloadFile, x));
}
function to_candid_SampleType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleType): _SampleType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TestCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestCategory): _TestCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Turnaround_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Turnaround): _Turnaround {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleType): {
    data: null;
} | {
    food: null;
} | {
    swab: null;
} | {
    extract: null;
} | {
    water: null;
} | {
    product: null;
} {
    return value == SampleType.data ? {
        data: null
    } : value == SampleType.food ? {
        food: null
    } : value == SampleType.swab ? {
        swab: null
    } : value == SampleType.extract ? {
        extract: null
    } : value == SampleType.water ? {
        water: null
    } : value == SampleType.product ? {
        product: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestCategory): {
    microbiology: null;
} | {
    pesticides: null;
} | {
    mycotoxins: null;
} | {
    heavyMetals: null;
} | {
    hormones: null;
} | {
    nutrients: null;
} | {
    residualSolvents: null;
} | {
    vitamins: null;
} {
    return value == TestCategory.microbiology ? {
        microbiology: null
    } : value == TestCategory.pesticides ? {
        pesticides: null
    } : value == TestCategory.mycotoxins ? {
        mycotoxins: null
    } : value == TestCategory.heavyMetals ? {
        heavyMetals: null
    } : value == TestCategory.hormones ? {
        hormones: null
    } : value == TestCategory.nutrients ? {
        nutrients: null
    } : value == TestCategory.residualSolvents ? {
        residualSolvents: null
    } : value == TestCategory.vitamins ? {
        vitamins: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Turnaround): {
    urgent: null;
} | {
    standard: null;
} {
    return value == Turnaround.urgent ? {
        urgent: null
    } : value == Turnaround.standard ? {
        standard: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TestCategory>): Array<_TestCategory> {
    return value.map((x)=>to_candid_TestCategory_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
